spring.application.name=gateway
server.port=9090
#EUREKA_Registery
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka


# ACTIVER GATEWAY
spring.cloud.gateway.discovery.locator.enabled=false
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# ROUTE COURSE
spring.cloud.gateway.routes[0].id=course
spring.cloud.gateway.routes[0].uri=lb://COURSE
spring.cloud.gateway.routes[0].predicates[0]=Path=/courses/**

# ROUTE TRAINING
spring.cloud.gateway.routes[1].id=certificat
spring.cloud.gateway.routes[1].uri=lb://certificat
spring.cloud.gateway.routes[1].predicates[0]=Path=/certificats/**

# ROUTE FORMATION
spring.cloud.gateway.routes[2].id=formation
spring.cloud.gateway.routes[2].uri=lb://Formation
spring.cloud.gateway.routes[2].predicates[0]=Path=/formations/**
# ROUTE FORMATION
spring.cloud.gateway.routes[3].id=eventGestion
spring.cloud.gateway.routes[3].uri=lb://eventGestion
spring.cloud.gateway.routes[3].predicates[0]=Path=/eventGestions/**
# ROUTE FORMATION
spring.cloud.gateway.routes[4].id=job-offer
spring.cloud.gateway.routes[4].uri=lb://job-offer
spring.cloud.gateway.routes[4].predicates[0]=Path=/job-offers/**
# ROUTE FORMATION
spring.cloud.gateway.routes[5].id=question
spring.cloud.gateway.routes[5].uri=lb://Question
spring.cloud.gateway.routes[5].predicates[0]=Path=/questions/**
# ROUTE FORMATION
spring.cloud.gateway.routes[6].id=users
spring.cloud.gateway.routes[6].uri=lb://USER
spring.cloud.gateway.routes[6].predicates[0]=Path=/users/**

# Forum Service Route
spring.cloud.gateway.routes[7].id=forum
spring.cloud.gateway.routes[7].uri=lb://FORUM
spring.cloud.gateway.routes[7].predicates[0]=Path=/forum/**

# Quiz Service Route
spring.cloud.gateway.routes[8].id=quiz
spring.cloud.gateway.routes[8].uri=lb://QUIZ
spring.cloud.gateway.routes[8].predicates[0]=Path=/quiz/**


# Global CORS Configuration for the Gateway
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:4200
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true
# Add this line to remove duplicate CORS headers
spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
# LOGS (pour voir le load balancing)
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG

